config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  get 'home/index'
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
	belongs_to :user
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:descriptions, :image)
    end
end

# I don't think he knows what he is doing instead of creating an id on the users table and check id's
# he is check is if that pin is assoicated with the user, which still works, but shouldn't you give 
# a user an id?
def correct_user
  @pin = current_user.pins.find_by(id: params[:id])
  redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark text-white">
  <%= link_to 'Pinterested', root_path, class: "navbar-brand text-white" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <!-- <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
      <li class="nav-item">
        <%= link_to 'home', root_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to 'About me', home_about_path, class: "nav-link text-white"  %>
      </li>

    </ul>
    <ul class="nav navbar-nav navbar-right">

      <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to 'List Pins', pins_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Add Pin', new_pin_path, class: "nav-link text-white" %>
        </li>
      <% else %>

        <li class="nav-item">
          <%= link_to 'Login', user_session_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Join', new_user_registration_path, class: "nav-link text-white" %>
        </li>

      <% end %>

    </ul>
  </div>
</nav>

app/views/home/about.html.erb
<h1>about Me! </h1>

app/views/home/index.html.erb
<br></br>
<div class="jumbotron center">
  <h1>Home of the pinterested app</h1>
  <p>Cool!</p>

  <% if user_signed_in? %>
  	<%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
  	<%= link_to 'Edit Profile', edit_user_registration_path, class: "btn btn-outline-secondary" %>
  	<%= link_to 'List Pins', pins_path, class: "btn btn-outline-secondary" %>
  <% else %>
  	<%= link_to 'Login', user_session_path, class: "btn btn-outline-primary" %>
  	<%= link_to 'Join', new_user_registration_path, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinterested</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/header' %>

    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin, html: {multipart: true} do |form| %> 
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
        <% pin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :descriptions %>
    <%= form.text_field :descriptions, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <br></br>
  <div class="actions">
    <%= form.submit 'submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<br></br>
<div class="card">
	<div class="card-header">
		Editing Pin
	</div>
	<div class="card-body">
		<%= render 'form', pin: @pin %>
	</div>
	<div class="card-footer text-muted">
		<%= link_to 'Show', @pin %> |
		<%= link_to 'Back', pins_path %>
	</div>
</div>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pins</h1>

<table>
  <thead>
    <tr>
      <th>Images</th>
      <th>Descriptions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= image_tag pin.image.url(:thumb) %> </td>
        <td><%= pin.descriptions %></td>
        <td><%= link_to 'Show', pin %></td>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<br></br>
<div class="card">
	<div class="card-header">
		New Pin
	</div>
	<div class="card-body">
		<%= render 'form', pin: @pin %>
	</div>
	<div class="card-footer text-muted">
		<%= link_to 'Back', pins_path %>
	</div>
</div>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @pin.image.url(:medium) %> 
  <br></br>
  <strong>Descriptions:</strong>
  <%= @pin.descriptions %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>